/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rsa;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.math.BigInteger;
import rsa.*;
import static rsa.RSA_.desencriptarXD;

/**
 *
 * @author user
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ayuda = new javax.swing.JPanel();
        Mensaje = new javax.swing.JTextField();
        cifrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        d = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        labelx = new javax.swing.JLabel();
        n = new javax.swing.JTextField();
        resultado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        desifrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 51));
        setPreferredSize(new java.awt.Dimension(400, 420));

        ayuda.setBackground(new java.awt.Color(255, 255, 255));
        ayuda.setForeground(new java.awt.Color(240, 240, 240));
        ayuda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Mensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MensajeActionPerformed(evt);
            }
        });
        ayuda.add(Mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 192, 275, -1));

        cifrar.setText("Cifrar");
        cifrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cifrarMouseClicked(evt);
            }
        });
        cifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cifrarActionPerformed(evt);
            }
        });
        ayuda.add(cifrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 310, 78, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Número:");
        ayuda.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 167, -1, -1));

        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });
        ayuda.add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 113, 50, -1));

        jLabel2.setBackground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("D:");
        ayuda.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 116, -1, -1));

        labelx.setBackground(new java.awt.Color(0, 51, 51));
        labelx.setText("N:");
        ayuda.add(labelx, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 116, -1, -1));
        ayuda.add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 113, 50, -1));
        ayuda.add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 238, 275, -1));

        jLabel3.setBackground(new java.awt.Color(51, 0, 51));
        jLabel3.setText("Resultado:");
        ayuda.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 218, -1, -1));

        desifrar.setText("Desifrar");
        desifrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                desifrarMouseClicked(evt);
            }
        });
        desifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desifrarActionPerformed(evt);
            }
        });
        ayuda.add(desifrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 310, 86, -1));
        ayuda.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 91, -1, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 51));
        jLabel5.setText("CIFRADO RSA");
        ayuda.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 32, -1, -1));

        jLabel6.setText("Martínez Zaragoza Alan Gael, 5IV8");
        ayuda.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 387, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        ayuda.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 376, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ayuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cifrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cifrarActionPerformed

    private void cifrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cifrarMouseClicked
        //Cifrar        
        String cadena = Mensaje.getText();
        RSA_ unu = new RSA_(10, cadena);

        BigInteger cifradoOb[] = unu.cifradoOb;
        BigInteger d = unu.d;
        BigInteger n = unu.n;
        this.d.setText(d.toString());
        this.n.setText(n.toString());
//        this.ayuda.set
//        this.ayuda2.setText(cifradoOb.toString());
        String mensaje_ = "";
        for (int i = 0; i < unu.getUnu(); i++) {
            mensaje_ += " " + cifradoOb[i];
        }
        mensaje_=mensaje_.substring(1,mensaje_.length());
        resultado.setText(mensaje_);
        
        
        
        File archivo;
        FileWriter fw;
        BufferedWriter bw;
        PrintWriter pw;
        
        try{
            
            
            
            
            archivo = new File("C:/Users/HP/Desktop/Cifrado.txt");
            archivo.delete();
            archivo = new File("C:/Users/HP/Desktop/Cifrado.txt");
            fw = new FileWriter(archivo);
            bw = new BufferedWriter(fw);
            pw = new PrintWriter(bw);
           
            
            pw.write("Cifrado: "+mensaje_+"\n"+"d: "+d+"\n"+"n: "+n);
            
            
            pw.close();
            bw.close();
            
            
            if (archivo.createNewFile()) {
                System.out.println("se ha creado");
            }
            
        }catch(IOException e){
            System.err.println("lkdn");
        }

    }//GEN-LAST:event_cifrarMouseClicked

    private void desifrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desifrarMouseClicked
        // Desifrar
//        String mensajekl = desencriptarXD(Resultado, d, n);
        BigInteger dBig = BigInteger.valueOf(Integer.parseInt(this.d.getText()));
        BigInteger nBig = BigInteger.valueOf(Integer.parseInt(this.n.getText()));
        String sCadena = Mensaje.getText() + " ";
//        sCadena = sCadena.substring(1, sCadena.length());
//        System.out.println("sCadena=" + sCadena + "df");
        String cadena2 = sCadena;
        char[] aCaracteres;
        aCaracteres = sCadena.toCharArray();
        int longi = 1;
        int xd = 1;
        for (int i = 0; xd > 0; i++) {
            cadena2 = cadena2.substring(cadena2.indexOf(" ") + 1);
            longi = longi + 1;
            if (cadena2.length() <= sCadena.indexOf(" ")) {
                xd = -1;
            }
        }
        cadena2 = sCadena;
        BigInteger[] ka = new BigInteger[longi - 1];
        for (int i = 0; i < longi - 1; i++) {
            ka[i] = BigInteger.valueOf(Integer.parseInt(cadena2.substring(0, cadena2.indexOf(" "))));
            cadena2 = cadena2.substring(cadena2.indexOf(" ") + 1);
        }
        System.out.println("ka = " + ka);
        String angela = RSA_.desencriptarXD(ka, dBig, nBig);
        resultado.setText(angela);
        
        
        
    }//GEN-LAST:event_desifrarMouseClicked
    private void desifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desifrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desifrarActionPerformed

    private void MensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MensajeActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Mensaje;
    private javax.swing.JPanel ayuda;
    private javax.swing.JButton cifrar;
    private javax.swing.JTextField d;
    private javax.swing.JButton desifrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelx;
    private javax.swing.JTextField n;
    private javax.swing.JTextField resultado;
    // End of variables declaration//GEN-END:variables
}
